In [6]:
import pandas as pd
from pathlib import Path
import matplotlib as plt

In [7]:
caminho = Path.home() / "Downloads" / "POP2022_Municipios.xls"

populacao_estados = pd.read_excel(caminho, header=1, skipfooter=34)
populacao_estados

      UF  COD. UF  COD. MUNIC      NOME DO MUNICÍPIO POPULAÇÃO
0     RO       11          15  Alta Floresta D'Oeste     21558
1     RO       11          23              Ariquemes    100896
2     RO       11          31                 Cabixi      5107
3     RO       11          49                 Cacoal     92202
4     RO       11          56             Cerejeiras     15237
...   ..      ...         ...                    ...       ...
5565  GO       52       22005             Vianópolis     14046
5566  GO       52       22054         Vicentinópolis      8776
5567  GO       52       22203               Vila Boa      3686
5568  GO       52       22302          Vila Propício      5646
5569  DF       53         108               Brasília   2923369

[5570 rows x 5 columns]

In [8]:
populacao_estados.info()

<class 'pandas.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   UF                 5570 non-null   str
 1   COD. UF            5570 non-null   int64
 2   COD. MUNIC         5570 non-null   int64
 3   NOME DO MUNICÍPIO  5570 non-null   str
 4   POPULAÇÃO          5570 non-null   object
dtypes: int64(2), object(1), str(2)
memory usage: 217.7+ KB

In [9]:
populacao_estados.describe()

           COD. UF    COD. MUNIC
count  5570.000000   5570.000000
mean     32.377738  15816.982585
std       9.833862  15997.299780
min      11.000000     13.000000
25%      25.000000   4507.250000
50%      31.000000  10400.500000
75%      41.000000  20853.000000
max      53.000000  72202.000000

In [10]:
populacao_estados.groupby("UF").sum(numeric_only=True)

    COD. UF  COD. MUNIC
UF
AC      264        7719
AL     2754      487914
AM      806      134451
AP      256        5908
BA    12093     7151757
CE     4232     1295156
DF       53         108
ES     2496      226710
GO    12792     2788737
MA     4557     1404205
MG    26443    31545374
MS     3950      355226
MT     7191      739592
PA     2160      643582
PB     5575     1941029
PE     4810     1524668
PI     4928     1275355
PR    16359     5760146
RJ     3036      287819
RN     4008     1276977
RO      572       35443
RR      210        4693
RS    21371     5903048
SC    12390     2894993
SE     2100      294557
SP    22575    18510133
TO     2363     1605293

In [12]:
# populacao_estados["População"].astype(int)

In [16]:
populacao_estados[populacao_estados["POPULAÇÃO"].str.contains('\(', na=False)]

<>:1: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
<>:1: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
/var/folders/_b/dnfcy9r13xvd5mtb_y7ckyd80000gn/T/ipykernel_9049/443481219.py:1: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
  populacao_estados[populacao_estados["POPULAÇÃO"].str.contains('\(', na=False)]

      UF  COD. UF  COD. MUNIC          NOME DO MUNICÍPIO    POPULAÇÃO
16    RO       11         205                Porto Velho   461.748(1)
74    AM       13          29                   Alvarães    15.916(2)
81    AM       13         409                   Barcelos    18.399(3)
83    AM       13         607          Benjamin Constant    37.436(4)
87    AM       13         805                      Borba    33.209(5)
88    AM       13         839                 Caapiranga    13.851(6)
97    AM       13        1605                  Fonte Boa    27.692(7)
98    AM       13        1654                    Guajará    13.809(8)
99    AM       13        1704                    Humaitá    59.504(9)
103   AM       13        1951                  Itamarati   10.783(10)
104   AM       13        2009                 Itapiranga   10.183(11)
105   AM       13        2108                     Japurá    9.281(12)
107   AM       13        2306                      Jutaí   25.048(13)
108   AM       13        2405                     Lábrea   47.003(14)
109   AM       13        2504                 Manacapuru  102.736(15)
117   AM       13        3205                 Novo Airão   15.819(16)
119   AM       13        3403                  Parintins   96.251(17)
120   AM       13        3502                     Pauini   20.351(18)
123   AM       13        3601  Santa Isabel do Rio Negro   14.305(19)
129   AM       13        4062                  Tabatinga   66.837(20)
134   AM       13        4302                    Urucará   18.582(21)
135   AM       13        4401                Urucurituba   24.017(22)
210   PA       15        3754               Jacareacanga   24.742(23)
579   MA       21        7506             Paço do Lumiar  145.752(24)
1526  PE       26        5509                  Ferreiros   15.040(25)
1937  BA       29        9208            Coronel João Sá   17.000(26)
1973  BA       29       12004                  Ibiassucê   10.426(27)
2159  BA       29       27101                    Rodelas   10.303(28)
4215  PR       41       21901         Ribeirão do Pinhal   13.053(29)
5509  GO       52       17609                 Planaltina  108.846(30)

In [19]:
populacao_estados = populacao_estados.assign(populacao_sem_parenteses = populacao_estados['POPULAÇÃO'].replace('\(\d{1,2}\)', '', regex = True),
                                             populacao = lambda x : x.loc[:, 'populacao_sem_parenteses'].replace('\.', '', regex = True))

<>:1: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
<>:2: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
<>:1: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
<>:2: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
/var/folders/_b/dnfcy9r13xvd5mtb_y7ckyd80000gn/T/ipykernel_9049/215950721.py:1: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
  populacao_estados = populacao_estados.assign(populacao_sem_parenteses = populacao_estados['POPULAÇÃO'].replace('\(\d{1,2}\)', '', regex = True),
/var/folders/_b/dnfcy9r13xvd5mtb_y7ckyd80000gn/T/ipykernel_9049/215950721.py:2: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
  populacao = lambda x : x.loc[:, 'populacao_sem_parenteses'].replace('\.', '', regex = True))

In [20]:
populacao_estados

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,POPULAÇÃO,populacao_sem_parenteses,populacao
0,RO,11,15,Alta Floresta D'Oeste,21558,21558,21558
1,RO,11,23,Ariquemes,100896,100896,100896
2,RO,11,31,Cabixi,5107,5107,5107
3,RO,11,49,Cacoal,92202,92202,92202
4,RO,11,56,Cerejeiras,15237,15237,15237
...,...,...,...,...,...,...,...
5565,GO,52,22005,Vianópolis,14046,14046,14046
5566,GO,52,22054,Vicentinópolis,8776,8776,8776
5567,GO,52,22203,Vila Boa,3686,3686,3686
5568,GO,52,22302,Vila Propício,5646,5646,5646
5569,DF,53,108,Brasília,2923369,2923369,2923369

In [21]:
populacao_estados["populacao"].astype(int)

0         21558
1        100896
2          5107
3         92202
4         15237
         ...
5565      14046
5566       8776
5567       3686
5568       5646
5569    2923369
Name: populacao, Length: 5570, dtype: int64

In [22]:
populacao_estados = populacao_estados.astype({"populacao": "int64"})

In [23]:
populacao_estados.info()

<class 'pandas.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   UF                        5570 non-null   str
 1   COD. UF                   5570 non-null   int64
 2   COD. MUNIC                5570 non-null   int64
 3   NOME DO MUNICÍPIO         5570 non-null   str
 4   POPULAÇÃO                 5570 non-null   object
 5   populacao_sem_parenteses  5570 non-null   object
 6   populacao                 5570 non-null   int64
dtypes: int64(3), object(2), str(2)
memory usage: 304.7+ KB

In [ ]:
populacao_estados = populacao_estados.groupby('UF')["populacao"].sum(numeric_only=True)

KeyError: 'Column not found: populacao'

In [27]:
populacao_estados = populacao_estados.reset_index()

In [28]:
populacao_estados

    UF  populacao
0   AC     829780
1   AL    3125254
2   AM    3952262
3   AP     774268
4   BA   14659023
5   CE    8936431
6   DF    2923369
7   ES    3975100
8   GO    6950976
9   MA    6800605
10  MG   20732660
11  MS    2833742
12  MT    3784239
13  PA    8442962
14  PB    4030961
15  PE    9051113
16  PI    3270174
17  PR   11835379
18  RJ   16615526
19  RN    3303953
20  RO    1616379
21  RR     634805
22  RS   11088065
23  SC    7762154
24  SE    2211868
25  SP   46024937
26  TO    1584306