In [1]:
import json
import pandas as pd

In [2]:
caminho = '/Users/samuelmacedo/Downloads/informacoes.json'

In [4]:
dados = pd.read_json(caminho)

In [5]:
dados

   nome  idade                                          enderecos
0  João     28  {'tipo': 'casa', 'rua': 'Rua A', 'numero': 123...
1  João     28  {'tipo': 'trabalho', 'rua': 'Rua B', 'numero':...

In [7]:
with open(caminho) as f:
    teste = json.load(f)

In [8]:
teste

{'nome': 'João',
 'idade': 28,
 'enderecos': [{'tipo': 'casa',
   'rua': 'Rua A',
   'numero': 123,
   'cidade': 'São Paulo'},
  {'tipo': 'trabalho',
   'rua': 'Rua B',
   'numero': 456,
   'cidade': 'Rio de Janeiro'}]}

In [16]:
normalizado = pd.json_normalize(teste, record_path='enderecos', meta=['nome', 'idade'])

In [17]:
normalizado

       tipo    rua  numero          cidade  nome idade
0      casa  Rua A     123       São Paulo  João    28
1  trabalho  Rua B     456  Rio de Janeiro  João    28

ValueError: column must be a scalar, tuple, or list thereof